### ISSUE TITLE
Set Date Range in wbn-datepicker Missing

### ISSUE THREAD

**Issue by abhishekdesigner** [Webinative/wbn-datepicker#3]
Hello,

I need to set date range for Adult, Child and infant..
Is there any options?
please help.

**Comment by mageshravi** [comment]
Yes, you can use as many groups of inputs as you want. Just make sure to use unique IDs for adult, child and infant.

E.g.,
`<input type="text" id="adult-from" class="form-control wbn-datepicker" />`
`<input type="text" id="adult-to" class="form-control wbn-datepicker" data-start-src="adult-from"/>`

`<input type="text" id="child-from" class="form-control wbn-datepicker" />`
`<input type="text" id="child-to" class="form-control wbn-datepicker" data-start-src="child-from"/>`

**Comment by abhishekdesigner** [comment]
Thank you for your reply..but these are in 2 input fields like adult from and adult to...But i m using single field for adult, second field for child and last field for infant.

I need to this kind of script like : yearRange: '1920:2000' something like that or whatelse

1, Adult Range is 1917 to 2005 
2, Child Range is 2005 to 2015 ( 2 year to 10 years )
3, Infant Range is 2015 to current year ( 0 to 2 years )
