### ISSUE TITLE
Set Range issues for Single Input field

### ISSUE THREAD

**Issue by abhishekdesigner** [Webinative/wbn-datepicker#4]
Thank you for your reply..but these are in 2 input fields which u sent like adult from and adult to...
But i m using single field for adult, second field for child and last field for infant.

I need to this kind of script like : yearRange: '1920:2000' something like that or whatelse

1, Adult Range is 1917 to 2005
2, Child Range is 2005 to 2015 ( 2 year to 10 years )
3, Infant Range is 2015 to current year ( 0 to 2 years )

**Comment by mageshravi** [comment]
You can use the `data-min` and `data-max` attributes to set min year and max year. Refer to the documentation or sample.html file.

**Comment by abhishekdesigner** [comment]
i used but this will be fix date ....and its not calculation with current date...

**Comment by mageshravi** [comment]
Currently, this plugin provides no such functionality. You will have to calculate the dates yourself using Javascript.

**Comment by abhishekdesigner** [comment]
Can you give me ideas? so i can do accordingly..
