### ISSUE TITLE
change values with jquery

### ISSUE THREAD

**Issue by pashaUSA** [Webinative/wbn-datepicker#5]
Is there an easy way to change date with jQuery line? 
I don't know, maybe something like $("selector").datepicker("change", "2015-05-12") and then  $("selector").datepicker("refresh"); 
Right now changing the value attribute doesn't resets the datepicker().

**Comment by mageshravi** [comment]
Thanks for pointing this out. I'm working on this. You can expect a fix ASAP.

**Comment by mageshravi** [comment]
You can set value for a datepicker element from JS like this,
`var $datepicker = $('#dp-element').datepicker()`
`$datepicker.val('2016-05-30')`
